apiVersion: v1
kind: Service
metadata:
  name: employee-server-service
spec:
  ports:
    - protocol: "TCP"
      port: 8445
      targetPort: 8445
  selector:
    app: employee-server
  type: NodePort